/**
 * @description       : 
 * @author            : Asadbek@i2max
 * @group             : 
 * @last modified on  : 09-21-2022
 * @last modified by  : Asadbek@i2max
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   09-16-2022   Asadbek@i2max   Initial Version
**/
public class httpCalloutService { 
    // HttpConfigration__c calloutMetadata;
    // String endpointUrl, requestMethod;
    // Map<String,String> urlParametersMap;
    // static final String TYPE_URL_PARAMETERS = 'URL_PARAMETERS';
    // HTTPRequest request;


    // public String getEndpointURL() {
    //     return endpointUrl;
    // }
    // public void setEndpointURL(String endpointUrl) {
    //     this.endpointUrl = endpointUrl;
    // }
    // public String getRequestMethod() {
    //     return requestMethod;
    // }
    // public void setRequestMethod(String requestMethod) {
    //     this.requestMethod = requestMethod;
    // }
    // public string getURLParameter(String key) {
    //     return urlParametersMap.get(key);
    // }
    // public Map<String,String> getURLParameter() {
    //     return urlParametersMap;
    // }
    // public void setUrlParameter(String key, String value) {
    //     if(String.isNotEmpty(key) && String.isNotEmpty(value)) {
    //         urlParametersMap.put(key, value);
    //     }
    //     else if(String.isNotEmpty(key)) {
    //         urlParametersMap.put(key, value);
    //     }
    // }
    // public void removeUrlParameter(String key) {
    //     urlParametersMap.remove(key);
    // }
}